FROM python:3.12-slim

ADD . /AuctionsAdmin
WORKDIR /AuctionsAdmin

COPY app.py /AuctionsAdmin/

RUN pip3 install -r requirements.txt

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]