FROM python:3.12-slim

WORKDIR /AuctionDBManager

COPY app.py /AuctionDBManager/
COPY AuctionEndpoints.py /AuctionDBManager/
COPY AuctionBidEndpoints.py /AuctionDBManager/
COPY requirements.txt /AuctionDBManager/

RUN pip3 install -r requirements.txt
RUN apt-get update && apt-get install -y \
    curl \
    apt-transport-https \
    gnupg2 \
    ca-certificates \
    lsb-release
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

RUN ACCEPT_EULA=Y apt-get install -y unixodbc-dev msodbcsql17
# msodbcsql17

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]