version: "3.8"

services:
  apigateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    container_name: apigateway
    depends_on:
      - dbmanager_gacha
      - gachasadmin
      - gachasuser
    ports:
      - "5000:5000"

  dbmanager_gacha:
    build:
      context: ./DBManagerGacha
      dockerfile: Dockerfile
    container_name: dbmanager_gacha

  gachasadmin:
    build:
      context: ./GatchasAdmin
      dockerfile: Dockerfile
    container_name: gachasadmin

  gachasuser:
    build:
      context: ./GatchasUser
      dockerfile: Dockerfile
    container_name: gachasuser