version: "3.8"

services:
  apigateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    container_name: apigateway
    depends_on:
      - authmicroservice
      - userdbmanager
    ports:
      - "5000:5000"
    volumes:
      - ./config.json:/app/config.json  # Mounts config.json into the container


  authmicroservice:
    build:
      context: ./AuthMicroservice
      dockerfile: Dockerfile
    container_name: authmicroservice
    depends_on:
      - authdatabase
    volumes:
      - ./config.json:/app/config.json
    secrets:
      - token_secret
      - auth_cert
      - auth_cert_key
  
  authdatabase:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Password1.
      - ACCEPT_EULA=Y
    container_name: authdatabase


  userdatabase:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Password1.
      - ACCEPT_EULA=Y
    container_name: userdatabase

  userdbmanager:
    build:
      context: ./UserDBManager
      dockerfile: Dockerfile
    container_name: userdbmanager
    depends_on:
      - userdatabase
    volumes:
      - ./config.json:/app/config.json

secrets:
  token_secret:
    file: ./secrets/token_secret.env
  auth_cert:
    file: ./secrets/auth_cert.pem
  auth_cert_key:
    file: ./secrets/auth_key.pem  