version: "3.8"

services:
  apigateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    container_name: apigateway
    depends_on:
      - auctionsadmin
      - auctionsuser
      - authadmin
      - authuser
      - authdbmanager
      - auctiondbmanager
      - userdbmanager
      - gachadbmanager
      - transactiondbmanager
      - paymentdbmanager
      - gachasadmin
      - gachasuser
      - paymentsadmin
      - paymentsuser
      - roll
      - transactionsadmin
      - transactionsuser
      - usersadmin
      - usersuser
    ports:
      - "5000:5000"
    volumes:
      - ./config.json:/app/config.json

  auctionsadmin:
    build:
      context: ./AuctionsAdmin
      dockerfile: Dockerfile
    container_name: auctionsadmin

  auctionsuser:
    build:
      context: ./AuctionsUser
      dockerfile: Dockerfile
    container_name: auctionsuser

  authadmin:
    build:
      context: ./AuthAdmin
      dockerfile: Dockerfile
    container_name: authadmin

  authuser:
    build:
      context: ./AuthUser
      dockerfile: Dockerfile
    container_name: authuser

  authdbmanager:
    build:
      context: ./AuthDBManager
      dockerfile: Dockerfile
    container_name: authdbmanager
    depends_on:
      - authdatabase
    volumes:
      - ./config.json:/app/config.json

  auctiondbmanager:
    build:
      context: ./AuctionDBManager
      dockerfile: Dockerfile
    container_name: auctiondbmanager
    depends_on:
      - auctiondatabase
    volumes:
      - ./config.json:/app/config.json

  gachadbmanager:
    build:
      context: ./GachaDBManager
      dockerfile: Dockerfile
    container_name: gachadbmanager
    depends_on:
      - gachadatabase
    volumes:
      - ./config.json:/app/config.json

  paymentdbmanager:
    build:
      context: ./PaymentDBManager
      dockerfile: Dockerfile
    container_name: paymentdbmanager
    depends_on:
      - paymentdatabase
    volumes:
      - ./config.json:/app/config.json

  transactiondbmanager:
    build:
      context: ./TransactionDBManager
      dockerfile: Dockerfile
    container_name: transactiondbmanager
    depends_on:
      - transactiondatabase
    volumes:
      - ./config.json:/app/config.json

  userdbmanager:
    build:
      context: ./UserDBManager
      dockerfile: Dockerfile
    container_name: userdbmanager
    depends_on:
      - userdatabase
    volumes:
      - ./config.json:/app/config.json

  authdatabase:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Password1.
      - ACCEPT_EULA=Y
    container_name: authdatabase

  gachadatabase:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Password1.
      - ACCEPT_EULA=Y
    container_name: gachadatabase

  userdatabase:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Password1.
      - ACCEPT_EULA=Y
    container_name: userdatabase

  paymentdatabase:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Password1.
      - ACCEPT_EULA=Y
    container_name: paymentdatabase

  auctiondatabase:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Password1.
      - ACCEPT_EULA=Y
    container_name: auctiondatabase
  
  transactiondatabase:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Password1.
      - ACCEPT_EULA=Y
    container_name: transactiondatabase

  gachasadmin:
    build:
      context: ./GatchasAdmin
      dockerfile: Dockerfile
    container_name: gachasadmin
    volumes:
      - ./config.json:/app/config.json

  gachasuser:
    build:
      context: ./GatchasUser
      dockerfile: Dockerfile
    container_name: gachasuser
    volumes:
      - ./config.json:/app/config.json

  paymentsadmin:
    build:
      context: ./PaymentsAdmin
      dockerfile: Dockerfile
    container_name: paymentsadmin
    volumes: 
      - ./config.json:/app/config.json

  paymentsuser:
    build:
      context: ./PaymentsUser
      dockerfile: Dockerfile
    container_name: paymentsuser
    volumes:
      - ./config.json:/app/config.json

  roll:
    build:
      context: ./Roll
      dockerfile: Dockerfile
    container_name: roll

  transactionsadmin:
    build:
      context: ./TransactionsAdmin
      dockerfile: Dockerfile
    container_name: transactionsadmin

  transactionsuser:
    build:
      context: ./TransactionsUser
      dockerfile: Dockerfile
    container_name: transactionsuser

  usersadmin:
    build:
      context: ./UsersAdmin
      dockerfile: Dockerfile
    container_name: usersadmin

  usersuser:
    build:
      context: ./UsersUser
      dockerfile: Dockerfile
    container_name: usersuser
