FROM python:3.12-slim

# layer caching for faster builds
COPY requirements.txt /
COPY auctioneer.py /
RUN pip install -r /requirements.txt

#COPY app.py /app.py

ADD . /Auctioneer
WORKDIR /Auctioneer

CMD ["python3", "auctioneer.py"]

