FROM python:3.12-slim

ADD . /TransactionsAdmin
WORKDIR /TransactionsAdmin

RUN pip3 install -r requirements.txt

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--cert=/run/secrets/transactions_ms_cert", "--key=/run/secrets/transactions_ms_key"]