FROM python:3.12-slim

ADD . /PaymentsMicroservice
WORKDIR /PaymentsMicroservice

COPY /config.json /app/

RUN pip3 install -r ./PaymentsMicroservice/requirements.txt

ENV FLASK_APP=./PaymentsMicroservice/app_test.py

EXPOSE 5000:5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]