FROM python:3.12-slim

ADD . /AuctionsMicroservice
WORKDIR /AuctionsMicroservice

COPY /code/config.json /app/
COPY /code/secrets/auction_ms_cert.pem /run/secrets/auction_ms_cert
COPY /code/secrets/auction_ms_key.pem /run/secrets/auction_ms_key

RUN pip3 install -r ./code/AuctionsMicroservice/requirements.txt

ENV FLASK_APP=./code/AuctionsMicroservice/app_test.py

EXPOSE 5001:5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--cert=/run/secrets/auction_ms_cert", "--key=/run/secrets/auction_ms_key"]