FROM python:3.12-slim

ADD . /AuctionsMicroservice
WORKDIR /AuctionsMicroservice

COPY config.json /app/
COPY /secrets/auction_ms_cert.pem /run/secrets/auction_ms_cert
COPY /secrets/auction_ms_key.pem /run/secrets/auction_ms_key

RUN pip3 install -r ./AuctionsMicroservice/requirements.txt

ENV FLASK_APP=./AuctionsMicroservice/app_test.py

EXPOSE 5001:5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--cert=/run/secrets/auction_ms_cert", "--key=/run/secrets/auction_ms_key"]