FROM python:3.12-slim

ADD . /UsersMicroservice
WORKDIR /UsersMicroservice

COPY /code/config.json /app/
COPY /code/secrets/users_cert.pem /run/secrets/users_cert
COPY /code/secrets/users_key.pem /run/secrets/users_cert_key


RUN pip3 install -r ./code/UsersMicroservice/requirements.txt

ENV FLASK_APP=./code/UsersMicroservice/app_test.py

EXPOSE 5000:5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--cert=/run/secrets/users_cert", "--key=/run/secrets/users_cert_key"]