FROM python:3.12-slim

ADD . /UsersAdmin
WORKDIR /UsersAdmin

COPY /config.json /app/

RUN pip3 install -r ./UsersAdmin/requirements.txt

ENV FLASK_APP=./UsersAdmin/app_test.py

EXPOSE 5000:5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]