FROM python:3.12-slim

ADD . /PaymentsMicroservice
WORKDIR /PaymentsMicroservice

COPY /config.json /app/
COPY /secrets/payments_cert.pem /run/secrets/payments_cert
COPY /secrets/payments_key.pem /run/secrets/payments_cert_key


RUN pip3 install -r ./PaymentsMicroservice/requirements.txt

ENV FLASK_APP=./PaymentsMicroservice/app_test.py

EXPOSE 5000:5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--cert=/run/secrets/payments_cert", "--key=/run/secrets/payments_cert_key"]