FROM python:3.12-slim

ADD . /GachaMicroservice
WORKDIR /GachaMicroservice

COPY config.json /app/

RUN pip3 install -r ./GachaMicroservice/requirements.txt

ENV FLASK_APP=./GachaMicroservice/app_test.py

EXPOSE 5000:5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]