
mock_gacha_list = [
    {"id": 1, "name": "Kuriboh", "description": "An adorable monster that defends you in battles.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/a/a4/Kuriboh.png", "rarityPercent": 1.0},
    {"id": 2, "name": "Winged Kuriboh", "description": "A winged version of Kuriboh with extra defense abilities.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/e/e4/WingedKuriboh.png", "rarityPercent": 2.0},
    {"id": 3, "name": "Baby Dragon", "description": "A small dragon with potential to grow stronger.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/7/79/BabyDragon.png", "rarityPercent": 3.0},
    {"id": 4, "name": "Giant Soldier of Stone", "description": "A giant made of stone that stands as a solid defense.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/8/80/GiantSoldierofStone.png", "rarityPercent": 5.0},
    {"id": 5, "name": "Mystical Elf", "description": "A sorceress with high defensive power.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/d/d6/MysticalElf.png", "rarityPercent": 10.0},
    {"id": 6, "name": "Celtic Guardian", "description": "An elf warrior that strikes with swift attacks.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/7/76/CelticGuardian.png", "rarityPercent": 15.0},
    {"id": 7, "name": "Man-Eater Bug", "description": "A nasty bug that destroys one monster upon flipping.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/5/55/ManEaterBug.png", "rarityPercent": 17.0},
    {"id": 8, "name": "Feral Imp", "description": "A beast with surprising power in battles.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/2/23/FeralImp.png", "rarityPercent": 19.0},
    {"id": 9, "name": "Harpie Lady", "description": "A bird-like warrior with swift attacks.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/7/7b/HarpieLady.png", "rarityPercent": 22.0},
    {"id": 10, "name": "Swordsman of Landstar", "description": "A humble swordsman with determination.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/c/c8/SwordsmanofLandstar.png", "rarityPercent": 23.0},
    {"id": 11, "name": "Spirit of the Harp", "description": "A spirit that brings harmony and high defense.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/e/e4/SpiritoftheHarp.png", "rarityPercent": 26.0},
    {"id": 12, "name": "Silver Fang", "description": "A wolf with sharp fangs for quick strikes.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/8/8f/SilverFang.png", "rarityPercent": 30.0},
    {"id": 13, "name": "Battle Ox", "description": "A beast-warrior that packs a punch in battle.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/8/8f/BattleOx.png", "rarityPercent": 33.0},
    {"id": 14, "name": "Armed Ninja", "description": "A stealthy ninja that flips the battle in your favor.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/4/4c/ArmedNinja.png", "rarityPercent": 36.0},
    {"id": 15, "name": "Dark Blade", "description": "A warrior who has mastered the blade.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/8/8d/DarkBlade.png", "rarityPercent": 41.0},
    {"id": 16, "name": "Luster Dragon", "description": "A shiny dragon that dazzles the battlefield.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/a/a8/LusterDragon.png", "rarityPercent": 44.0},
    {"id": 17, "name": "Penguin Soldier", "description": "A strategic penguin that bounces enemies back to hand.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/1/11/PenguinSoldier.png", "rarityPercent": 47.0},
    {"id": 18, "name": "Dragon Zombie", "description": "A dragon that rose from the dead with reduced power.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/9/9f/DragonZombie.png", "rarityPercent": 49.0},
    {"id": 19, "name": "Rogue Doll", "description": "A mystical doll with unpredictable attacks.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/d/db/RogueDoll.png", "rarityPercent": 50.0},
    {"id": 20, "name": "Time Wizard", "description": "A wizard that manipulates time to change battles.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/4/41/TimeWizard.png", "rarityPercent": 50.0},
    {"id": 21, "name": "Thousand Dragon", "description": "The elder form of Baby Dragon after time travel.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/4/42/ThousandDragon.png", "rarityPercent": 53.0},
    {"id": 22, "name": "The Shadow Who Controls the Dark", "description": "A sinister shadow with hidden power.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/a/ac/ShadowWhoControlsDark.png", "rarityPercent": 55.0},
    {"id": 23, "name": "Dark Mimic LV1", "description": "A mimic that tricks enemies in battle.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/3/36/DarkMimicLV1.png", "rarityPercent": 50.0},
    {"id": 24, "name": "Destruction Punch", "description": "A punch that shatters opponents.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/5/50/DestructionPunch.png", "rarityPercent": 60.0},
    {"id": 25, "name": "Summoned Skull", "description": "A fiend with dark powers for confusing the enemy.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/d/db/SummonedSkull.png", "rarityPercent": 62.0},
    {"id": 26, "name": "Gemini Elf", "description": "A pair of elves that attack as one.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/7/71/GeminiElf.png", "rarityPercent": 64.0},
    {"id": 27, "name": "Dark Magician Girl", "description": "The apprentice of the ultimate wizard in terms of attack and defense.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/3/30/DarkMagicianGirl.png", "rarityPercent": 66.9},
    {"id": 28, "name": "Breaker the Magical Warrior", "description": "A powerful spellcaster with destructive capabilities.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/9/9b/BreakerTheMagicalWarrior.png", "rarityPercent": 70.0},
    {"id": 29, "name": "Cyber Dragon", "description": "A mechanical dragon that can summon itself to the field quickly.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/e/eb/CyberDragon.png", "rarityPercent": 71.0},
    {"id": 30, "name": "Red-Eyes Black Dragon", "description": "A ferocious dragon with devastating power.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/4/45/RedEyesBlackDragon.png", "rarityPercent": 74.0},
    {"id": 31, "name": "Buster Blader", "description": "A dragon-slaying warrior with immense attack power.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/2/22/BusterBlader.png", "rarityPercent": 77.0},
    {"id": 32, "name": "Mystical Space Typhoon", "description": "A spell that destroys one spell or trap card on the field.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/6/6b/MysticalSpaceTyphoon.png", "rarityPercent": 79.0},
    {"id": 33, "name": "Blue-Eyes Toon Dragon", "description": "A cartoonish version of the Blue-Eyes White Dragon.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/d/dd/BlueEyesToonDragon.png", "rarityPercent": 80.0},
    {"id": 34, "name": "Dark Paladin", "description": "The ultimate fusion of Dark Magician and Buster Blader.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/3/37/DarkPaladin.png", "rarityPercent": 82.0},
    {"id": 35, "name": "Toon Mermaid", "description": "A playful toon monster that can attack directly.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/e/e6/ToonMermaid.png", "rarityPercent": 85.0},
    {"id": 36, "name": "Blue-Eyes White Dragon", "description": "The legendary dragon with an overwhelming attack power.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/2/2c/BlueEyesWhiteDragon.png", "rarityPercent": 87.0},
    {"id": 37, "name": "Dark Magician", "description": "The ultimate wizard in terms of attack and defense.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/9/9e/DarkMagician.png", "rarityPercent": 89.0},
    {"id": 38, "name": "Exodia the Forbidden One", "description": "One of the most powerful cards, capable of ending the game when assembled.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/3/31/ExodiaTheForbiddenOne.png", "rarityPercent": 92.0},
    {"id": 39, "name": "Obelisk the Tormentor", "description": "A god card with unmatched destructive power.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/7/7f/ObeliskTheTormentor.png", "rarityPercent": 94.0},
    {"id": 40, "name": "Slifer the Sky Dragon", "description": "A god card with incredible power scaling with your hand.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/a/a2/SliferTheSkyDragon.png", "rarityPercent": 97.0},
    {"id": 41, "name": "The Dragon of Light, Horakhty", "description": "The ultimate Dragon card, with the power to end the game instantly.",
        "image": "https://static.wikia.nocookie.net/yugioh/images/4/4d/TheCreatorGodofLightHorakhty.png", "rarityPercent": 98.0},
    {"id": 42, "name": "The Winged Dragon of Ra", "description": "The most powerful god card, with limitless potential.", 
     "image": "https://static.wikia.nocookie.net/yugioh/images/4/4d/TheWingedDragonofRa.png", "rarityPercent": 99.0}
]

mock_gacha_collection_list = [
        {
            'id': 1,
            'gachaId': 1,
            'userId': 1,
            'timestamp': '2021-07-01T12:00:00',
            'source': 'ROLL'
        },
        {
            'id': 2,
            'gachaId': 2,
            'userId': 1,
            'timestamp': '2021-07-01T12:01:00',
            'source': 'AUCTION'
        },
        {
            'id': 3,
            'gachaId': 3,
            'userId': 2,
            'timestamp': '2021-07-01T12:02:00',
            'source': 'ROLL'
        }
    ]

mock_user_list = [
        {
            'id': 1,
            'authId': 101,
            'ingameCurrency': 1500.0,
            'profilePicture': 'profile1.png',
            'registrationDate': '2021-01-01T10:00:00',
            'status': 'ACTIVE'
        },
        {
            'id': 2,
            'authId': 102,
            'ingameCurrency': 3000.0,
            'profilePicture': 'profile2.png',
            'registrationDate': '2021-02-01T11:00:00',
            'status': 'ACTIVE'
        },
        {
            'id': 3,
            'authId': 103,
            'ingameCurrency': 0.0,
            'profilePicture': 'profile3.png',
            'registrationDate': '2021-03-01T12:00:00',
            'status': 'ACTIVE'
        }
    ]