FROM python:3.12-slim

ADD . /PaymentsAdmin
WORKDIR /PaymentsAdmin

COPY /config.json /app/

RUN pip3 install -r ./PaymentsAdmin/requirements.txt

ENV FLASK_APP=./PaymentsAdmin/app_test.py

EXPOSE 5000:5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]