FROM python:3.12-slim

WORKDIR /ApiGatewayUser
ADD * /ApiGatewayUser

RUN pip3 install -r requirements.txt

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--cert=/run/secrets/gateway_user_cert", "--key=/run/secrets/gateway_user_key"]