FROM amd64/python:3.12.0b1-slim-buster

ADD . /AuthMicroservice
WORKDIR /AuthMicroservice

RUN pip3 install -r requirements.txt
RUN apt-get update && apt-get install -y \
    curl \
    apt-transport-https \
    gnupg2 \
    ca-certificates \
    lsb-release
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

RUN apt-get update 

#&& apt-get install -y curl gnupg2 ca-certificates lsb-release
RUN ACCEPT_EULA=Y apt-get install -y unixodbc-dev msodbcsql17
EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--cert=/run/secrets/auth_cert", "--key=/run/secrets/auth_cert_key"]
